# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8050720809f2f7e3784e7bb7768549cbad623bf4cc783d042a6397397b0f7ed3118c3ac12d5e369be3a7a9a8f0e8ba48ae6a7eee8d34c9fe4e869130ff5eb2c7

test:
  secret_key_base: d6d447b4560d473b36f99017adf940eee5232cac01e3525c5455474df333d7b4c9b2c04d74ab7dfde4839efe8e67f7f9ea9a49cd9764a0db1c32d3e5e07b8c4e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
